-- =============================================================
-- Script de creación de base de datos: Fábrica de Hilos
-- Base de datos: Oracle
-- Esquema: FABRICA_HILOS
-- =============================================================

-- Crear usuario/esquema (ejecutar como DBA)
-- CREATE USER FABRICA_HILOS IDENTIFIED BY "contraseña_segura";
-- GRANT CONNECT, RESOURCE TO FABRICA_HILOS;
-- GRANT CREATE SESSION TO FABRICA_HILOS;

-- =============================================================
-- Tabla: HILOS
-- =============================================================
CREATE TABLE HILOS (
    ID               NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CODIGO           VARCHAR2(20)    NOT NULL,
    NOMBRE           VARCHAR2(100)   NOT NULL,
    DESCRIPCION      VARCHAR2(500),
    COLOR            VARCHAR2(50)    NOT NULL,
    GRAMAJE_POR_ROLLO NUMBER(10, 2)  NOT NULL,
    STOCK            NUMBER(10)      NOT NULL DEFAULT 0,
    PRECIO           NUMBER(12, 2)   NOT NULL,
    FECHA_CREACION   DATE            NOT NULL DEFAULT SYSDATE,
    ACTIVO           NUMBER(1)       NOT NULL DEFAULT 1,
    CONSTRAINT CHK_HILOS_ACTIVO CHECK (ACTIVO IN (0, 1)),
    CONSTRAINT UQ_HILOS_CODIGO  UNIQUE (CODIGO)
);

CREATE INDEX IDX_HILOS_NOMBRE ON HILOS (NOMBRE);

-- =============================================================
-- Tabla: MATERIALES
-- =============================================================
CREATE TABLE MATERIALES (
    ID              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NOMBRE          VARCHAR2(100)  NOT NULL,
    DESCRIPCION     VARCHAR2(500),
    UNIDAD_MEDIDA   VARCHAR2(20)   NOT NULL,
    STOCK           NUMBER(14, 2)  NOT NULL DEFAULT 0,
    COSTO_UNITARIO  NUMBER(12, 2)  NOT NULL,
    ACTIVO          NUMBER(1)      NOT NULL DEFAULT 1,
    CONSTRAINT CHK_MATERIALES_ACTIVO CHECK (ACTIVO IN (0, 1))
);

CREATE INDEX IDX_MATERIALES_NOMBRE ON MATERIALES (NOMBRE);

-- =============================================================
-- Tabla: CLIENTES
-- =============================================================
CREATE TABLE CLIENTES (
    ID              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NOMBRE          VARCHAR2(100)  NOT NULL,
    APELLIDO        VARCHAR2(100)  NOT NULL,
    EMAIL           VARCHAR2(200)  NOT NULL,
    TELEFONO        VARCHAR2(20),
    DIRECCION       VARCHAR2(300),
    FECHA_REGISTRO  DATE           NOT NULL DEFAULT SYSDATE,
    ACTIVO          NUMBER(1)      NOT NULL DEFAULT 1,
    CONSTRAINT CHK_CLIENTES_ACTIVO CHECK (ACTIVO IN (0, 1)),
    CONSTRAINT UQ_CLIENTES_EMAIL    UNIQUE (EMAIL)
);

CREATE INDEX IDX_CLIENTES_APELLIDO ON CLIENTES (APELLIDO, NOMBRE);

-- =============================================================
-- Tabla: PEDIDOS
-- =============================================================
CREATE TABLE PEDIDOS (
    ID              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NUMERO          VARCHAR2(20)   NOT NULL,
    CLIENTE_ID      NUMBER         NOT NULL,
    FECHA_PEDIDO    DATE           NOT NULL DEFAULT SYSDATE,
    FECHA_ENTREGA   DATE,
    ESTADO          VARCHAR2(30)   NOT NULL DEFAULT 'Pendiente',
    TOTAL           NUMBER(14, 2)  NOT NULL DEFAULT 0,
    OBSERVACIONES   VARCHAR2(500),
    CONSTRAINT FK_PEDIDOS_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTES(ID),
    CONSTRAINT CHK_PEDIDOS_ESTADO CHECK (ESTADO IN ('Pendiente', 'En Proceso', 'Completado', 'Cancelado')),
    CONSTRAINT UQ_PEDIDOS_NUMERO  UNIQUE (NUMERO)
);

CREATE INDEX IDX_PEDIDOS_CLIENTE   ON PEDIDOS (CLIENTE_ID);
CREATE INDEX IDX_PEDIDOS_FECHA     ON PEDIDOS (FECHA_PEDIDO DESC);
CREATE INDEX IDX_PEDIDOS_ESTADO    ON PEDIDOS (ESTADO);

-- =============================================================
-- Tabla: DETALLE_PEDIDOS
-- =============================================================
CREATE TABLE DETALLE_PEDIDOS (
    ID              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    PEDIDO_ID       NUMBER         NOT NULL,
    HILO_ID         NUMBER         NOT NULL,
    CANTIDAD        NUMBER(10)     NOT NULL,
    PRECIO_UNITARIO NUMBER(12, 2)  NOT NULL,
    CONSTRAINT FK_DETALLE_PEDIDO FOREIGN KEY (PEDIDO_ID) REFERENCES PEDIDOS(ID),
    CONSTRAINT FK_DETALLE_HILO   FOREIGN KEY (HILO_ID)   REFERENCES HILOS(ID),
    CONSTRAINT CHK_DETALLE_CANTIDAD CHECK (CANTIDAD > 0)
);

CREATE INDEX IDX_DETALLE_PEDIDO ON DETALLE_PEDIDOS (PEDIDO_ID);
CREATE INDEX IDX_DETALLE_HILO   ON DETALLE_PEDIDOS (HILO_ID);

-- =============================================================
-- Datos de ejemplo
-- =============================================================
INSERT INTO HILOS (CODIGO, NOMBRE, DESCRIPCION, COLOR, GRAMAJE_POR_ROLLO, STOCK, PRECIO)
VALUES ('H-001', 'Hilo Algodón Blanco', 'Hilo de algodón 100% natural', 'Blanco', 100, 50, 15.99);

INSERT INTO HILOS (CODIGO, NOMBRE, DESCRIPCION, COLOR, GRAMAJE_POR_ROLLO, STOCK, PRECIO)
VALUES ('H-002', 'Hilo Algodón Rojo', 'Hilo de algodón teñido', 'Rojo', 100, 30, 17.50);

INSERT INTO HILOS (CODIGO, NOMBRE, DESCRIPCION, COLOR, GRAMAJE_POR_ROLLO, STOCK, PRECIO)
VALUES ('H-003', 'Hilo Poliéster Azul', 'Hilo sintético resistente', 'Azul', 200, 100, 12.00);

INSERT INTO MATERIALES (NOMBRE, DESCRIPCION, UNIDAD_MEDIDA, STOCK, COSTO_UNITARIO)
VALUES ('Algodón Natural', 'Fibra de algodón sin procesar', 'kg', 500, 8.50);

INSERT INTO MATERIALES (NOMBRE, DESCRIPCION, UNIDAD_MEDIDA, STOCK, COSTO_UNITARIO)
VALUES ('Colorante Rojo', 'Colorante textil industrial', 'kg', 20, 45.00);

INSERT INTO CLIENTES (NOMBRE, APELLIDO, EMAIL, TELEFONO, DIRECCION)
VALUES ('Juan', 'García', 'juan.garcia@ejemplo.com', '+54 11 1234-5678', 'Av. Corrientes 1234, CABA');

INSERT INTO CLIENTES (NOMBRE, APELLIDO, EMAIL, TELEFONO, DIRECCION)
VALUES ('María', 'López', 'maria.lopez@ejemplo.com', '+54 11 8765-4321', 'Calle Florida 567, CABA');

COMMIT;
