-- =============================================================
-- Script: Tabla PREPARATORIA
-- Base de datos: Oracle
-- Esquema: FABRICA_HILOS
-- Descripción: Registros de procesos de preparación de materias
--              primas previos a la producción de hilos.
-- =============================================================

-- =============================================================
-- Tabla: PREPARATORIA
-- =============================================================
CREATE TABLE PREPARATORIA (
    ID                    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CODIGO                VARCHAR2(20)   NOT NULL,
    FECHA_INICIO          DATE           NOT NULL DEFAULT SYSDATE,
    FECHA_FIN_ESTIMADA    DATE,
    HILO_ID               NUMBER         NOT NULL,
    MATERIAL_ID           NUMBER         NOT NULL,
    CANTIDAD_PLANIFICADA  NUMBER(14, 2)  NOT NULL,
    CANTIDAD_PROCESADA    NUMBER(14, 2)  NOT NULL DEFAULT 0,
    ESTADO                VARCHAR2(30)   NOT NULL DEFAULT 'Pendiente',
    RESPONSABLE           VARCHAR2(100),
    OBSERVACIONES         VARCHAR2(500),
    FECHA_CREACION        DATE           NOT NULL DEFAULT SYSDATE,
    ACTIVO                NUMBER(1)      NOT NULL DEFAULT 1,
    CONSTRAINT FK_PREP_HILO     FOREIGN KEY (HILO_ID)     REFERENCES HILOS(ID),
    CONSTRAINT FK_PREP_MATERIAL FOREIGN KEY (MATERIAL_ID) REFERENCES MATERIALES(ID),
    CONSTRAINT CHK_PREP_ESTADO  CHECK (ESTADO IN ('Pendiente', 'En Proceso', 'Completado', 'Cancelado')),
    CONSTRAINT CHK_PREP_ACTIVO  CHECK (ACTIVO IN (0, 1)),
    CONSTRAINT UQ_PREP_CODIGO   UNIQUE (CODIGO)
);

CREATE INDEX IDX_PREP_HILO     ON PREPARATORIA (HILO_ID);
CREATE INDEX IDX_PREP_MATERIAL ON PREPARATORIA (MATERIAL_ID);
CREATE INDEX IDX_PREP_FECHA    ON PREPARATORIA (FECHA_INICIO DESC);
CREATE INDEX IDX_PREP_ESTADO   ON PREPARATORIA (ESTADO);

-- =============================================================
-- Query para insertar registro PREPARATORIA
-- =============================================================
INSERT INTO PREPARATORIA (
    CODIGO,
    FECHA_INICIO,
    FECHA_FIN_ESTIMADA,
    HILO_ID,
    MATERIAL_ID,
    CANTIDAD_PLANIFICADA,
    CANTIDAD_PROCESADA,
    ESTADO,
    RESPONSABLE,
    OBSERVACIONES
) VALUES (
    'PREP-001',
    SYSDATE,
    SYSDATE + 7,
    1,
    1,
    500,
    0,
    'Pendiente',
    'Carlos Ramírez',
    'Preparación inicial de algodón para hilo blanco'
);

COMMIT;
